Set `rc_dir` based on `W3M_DIR` environment variable.
tats/w3m pull request #207
Opened 2021-12-12 08:13 UTC by yashlala

By default, w3m puts all of its data in the `~/.w3m/` directory (creating it as necessary). This was not configurable in any way.

This commit addresses this problem. When the `W3M_DIR` environment variable is set, w3m will use its contents to store its data files instead. The default location is unchanged.

This PR should resolve issue #130. Sorry for the delay :)

2021-12-12 17:24 UTC, rkta requested changes
This patch series has a lot of trailing whitespace, would you mind removing them?

git diff --check HEAD~1

will show them.

2021-12-12 18:06 UTC, rkta reviewed
And while we are at it, we might want to remove the commented out printfs. I don't think they carry any value.

2021-12-12 20:22 UTC, yashlala commented
Thanks for the feedback @rkta -- I've made the changes you suggested (+ some minor fixes).

2021-12-13 18:19 UTC, rkta commented
I had a closer look and found another more serious issue. 

PATH_MAX is problematic, but I'm ok with its use here. Though the strncpy(component, dir, sizeof(component)); needs an error check.

And I would squash those commits, but that's not on me to decide. Otherwise LGTM.

Thanks!

2021-12-15 02:19 UTC, yashlala commented
Thanks for catching the `strncpy` bug -- the latest push should fix it. I've updated to  a proper `malloc` style implementation to address the former reservation. 

I was under the impression that squashing (if desired) happens when merging -- I can squash them now no problem though.

2021-12-15 12:02 UTC, rkta commented
With this changes we don't need limits.h anymore, do we?

2021-12-15 17:58 UTC, yashlala commented
Fixed. I appreciate your patience.

2021-12-15 18:13 UTC, rkta approved these changes
LGTM! Thanks for _your_ patience. ;)

2022-01-14 16:22 UTC, rkta commented
One more thing:

rc.c: In function ‘init_rc’:
rc.c:1353:17: warning: unused variable ‘st’ [-Wunused-variable]
 1353 |     struct stat st;
      |                 ^~

Sorry for being that late.

2022-01-14 19:08 UTC, yashlala commented
Fixed.

2022-06-01 11:49 UTC, butyoutried commented
I hope this will be merged eventually. It's a useful feature.

2022-06-01 11:59 UTC, N-R-K commented on rc.c
> +    strcpy(dircpy, dir);
Any reason for not using `strdup(3)` ?

2022-06-03 01:03 UTC, yashlala commented on rc.c
> +    strcpy(dircpy, dir);
Inexperience. I've added it now.

2022-06-03 01:16 UTC, yashlala commented
@rkta The syscall below needs a `const char *`, so I'd have to break encapsulation anyways (+ I thought the Str getters and indexing would overcomplicate the function). `do_mkdir` got away with standard C, so I followed :)

Is there a reason you'd prefer that construct?

2022-06-03 06:43 UTC, rkta commented
On Thu, Jun 02, 2022 at 06:16:55PM -0700, yashlala wrote:
> @rkta The syscall below needs a `const char *`, so I'd have to break
> encapsulation anyways (+ I thought the Str getters and indexing would
> overcomplicate the function). `do_mkdir` got away with standard C, so
> I followed :)

Instead of:
    if ((dircpy = malloc(n + 1)) == NULL)
      return -1;
    strcpy(dircpy, dir);

you can do:
    dircpy = Strnew_charp(dir)->ptr;

and you don't need to care about malloc() and free(). Strnew_charp()
will exit(1) if malloc() fails and garbage collect the memory if it's
not used anymore.


> Is there a reason you'd prefer that construct? 

I'd say it's the common pattern used in the code base, but it's not
really that important.

2022-06-04 00:10 UTC, yashlala commented
Huh. I'm amazed the garbage collector can differentiate C pointer data from integer data to that degree of confidence. 

I've made the change you suggested. Please let me know if there's anything else I should do.

2022-07-01 19:04 UTC, yashlala commented
Hi @N-R-K ; Github is telling me that you need to review this before the patch can be merged into main, so I'm reaching out again. If there's anything I need to do before it's ready for upstream, I'm happy to do so.

2022-07-01 19:11 UTC, N-R-K commented
> Github is telling me that you need to review this before the patch can be merged into main

Huh, I think that's just some generic UI thing. I'm not the maintainer or this project (@tats is) nor am I in any position to decide what gets merged to master.

2022-07-01 19:22 UTC, yashlala commented
Alright then. @tats -- unless you have suggestions, I think this PR is finalized and ready to merge.

2022-08-22 07:01 UTC, ignamartinoli commented
Any update?

2022-08-22 21:51 UTC, tats commented
I plan to merge this, though still XDG-non-compliant.

2022-12-21 11:20 UTC, merged

2022-12-21 11:20 UTC, tats commented
Merged, thanks for your contribution.